apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP   # accessible uniquement depuis l'intérieur du cluster, pas depuis internet
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
